#Expyriment 1.0.0 (Python 3.12.7), .xpe-file, coding: cp936
#date: Wed Sep 24 2025 18:03:51
#sha1: e4c2e0
#modules: 
#display: size=(800, 600), window_mode=False, opengl=2
#os: uname_result(system='Windows', node='LmysFriend', release='11', version='10.0.26100', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
10513,design,log,
#design: #exp: Display Edges
#design: block_cnt,block_id,trial_cnt,trial_id
10513,design,logged,
10513,Experiment,started
10515,stderr,received,'Traceback (most recent call last):'
10515,stderr,received,'  File "e:\\CSFile\\CogSup\\Programming\\Materials\\Week-3\\Exercises\\display-edges.py", line 8, in <module>'
10515,stderr,received,'    exp.control.start()'
10515,stderr,received,'  File "E:\\Anaconda\\Lib\\site-packages\\expyriment\\control\\_experiment_control.py", line 59, in start'
10516,stderr,received,'    raise Exception("Experiment is already started!")'
10516,stderr,received,'Exception: Experiment is already started!'
